CREATE TABLE bet (
id INT NOT NULL AUTO_INCREMENT,
description VARCHAR(255) NOT NULL,
active TINYINT DEFAULT 1 NOT NULL,
primary key (id)
);

CREATE TABLE `option` (
id INT NOT NULL AUTO_INCREMENT,
description VARCHAR(255) NOT NULL,
betId INT NOT NULL,
primary key (id),
FOREIGN KEY (betId) REFERENCES bet(id) ON DELETE CASCADE ON UPDATE CASCADE
);